
=encoding utf8

=head1 REVISION HISTORY FOR IO::Plumbing

=head2 0.06, 8 Jul 2008

=over

=item *

Module::Install didn't update META.yml.  So, here is another release.

=back

=head2 0.05, 8 Jul 2008

=over

=item *

Brown paper bag release - fix a broken test.

=back

=head2 0.04, 8 Jul 2008

=over

=item *

Fix some test failures that were due to 'od -x' having different
output across systems

=back

=head2 0.03, 23 Jun 2008

Selection of features:

=over

=item *

Fix the MANIFEST.SKIP so we actually deliver a Makefile.PL

=item *

Add new "hose" object

=item *

Plumb connection refactor

=item *

Vague beginnings of fd_shape for custom-shaped plumbs

=back

=head2 0.02, 29 Apr 2008

=over

=item *

Update dependencies, correct usage of Module::Install

=item *

Move use of $PREFER_CODE to where it was defined.

=back

=cut

